'use strict';
/**
 * CLAWTRAP Full Architecture Simulation
 * ======================================
 * Faithfully implements: DFS maze gen, BFS pathfinding, Director Deck (30 cards),
 * card skip logic, HP management, pressure effects, trial system, exit conditions,
 * temptation mechanics, 66-step limit, God's Hand, Retreat.
 *
 * Reads: villain-content.json + player-decisions.json (generated by subagents)
 * Outputs: complete game log to stdout
 */
const fs = require('fs');
const path = require('path');

// ═══════════════════════════════════════════════════════════════
// SEEDED RNG (deterministic simulation)
// ═══════════════════════════════════════════════════════════════
let _seed = 42;
function rng() {
  _seed = (_seed * 16807 + 0) % 2147483647;
  return (_seed - 1) / 2147483646;
}
function rngInt(min, max) { return min + Math.floor(rng() * (max - min + 1)); }
function rngPick(arr) { return arr[Math.floor(rng() * arr.length)]; }

// ═══════════════════════════════════════════════════════════════
// MAZE GENERATION (DFS, identical to js/core.js)
// ═══════════════════════════════════════════════════════════════
const GRID_W = 21, GRID_H = 27;
const CELL_WALL = 0, CELL_PATH = 1, CELL_EXIT = 2;

function generateMaze() {
  const maze = Array.from({ length: GRID_H }, () => Array(GRID_W).fill(CELL_WALL));
  const stack = [{ x: 1, y: 1 }];
  maze[1][1] = CELL_PATH;

  while (stack.length > 0) {
    const { x, y } = stack[stack.length - 1];
    const dirs = [
      { dx: 0, dy: -2 }, { dx: 0, dy: 2 },
      { dx: -2, dy: 0 }, { dx: 2, dy: 0 },
    ].filter(d => {
      const nx = x + d.dx, ny = y + d.dy;
      return nx > 0 && nx < GRID_W - 1 && ny > 0 && ny < GRID_H - 1 && maze[ny][nx] === CELL_WALL;
    });

    if (dirs.length === 0) { stack.pop(); continue; }
    const d = dirs[Math.floor(rng() * dirs.length)];
    const nx = x + d.dx, ny = y + d.dy;
    maze[y + d.dy / 2][x + d.dx / 2] = CELL_PATH;
    maze[ny][nx] = CELL_PATH;
    stack.push({ x: nx, y: ny });
  }

  // Place exit at bottom-right area
  let exitX = GRID_W - 2, exitY = GRID_H - 2;
  if (maze[exitY][exitX] === CELL_WALL) {
    // Find nearest path cell to bottom-right
    for (let dy = 0; dy < GRID_H; dy++) {
      for (let dx = 0; dx < GRID_W; dx++) {
        const ty = GRID_H - 1 - dy, tx = GRID_W - 1 - dx;
        if (maze[ty][tx] === CELL_PATH) { exitX = tx; exitY = ty; dy = GRID_H; break; }
      }
    }
  }
  maze[exitY][exitX] = CELL_EXIT;
  return { maze, start: { x: 1, y: 1 }, exit: { x: exitX, y: exitY } };
}

// ═══════════════════════════════════════════════════════════════
// BFS PATHFINDING
// ═══════════════════════════════════════════════════════════════
function findPath(maze, start, end) {
  const key = (x, y) => `${x},${y}`;
  const queue = [{ ...start, path: [{ ...start }] }];
  const visited = new Set([key(start.x, start.y)]);

  while (queue.length > 0) {
    const { x, y, path: p } = queue.shift();
    if (x === end.x && y === end.y) return p;

    for (const [dx, dy] of [[0, -1], [0, 1], [-1, 0], [1, 0]]) {
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || nx >= GRID_W || ny < 0 || ny >= GRID_H) continue;
      if (maze[ny][nx] === CELL_WALL) continue;
      const k = key(nx, ny);
      if (visited.has(k)) continue;
      visited.add(k);
      queue.push({ x: nx, y: ny, path: [...p, { x: nx, y: ny }] });
    }
  }
  return null; // no path found (shouldn't happen with DFS maze)
}

// Get neighbors (walkable adjacent cells)
function getNeighbors(maze, x, y) {
  const result = [];
  for (const [dx, dy, dir] of [[0, -1, 'N'], [0, 1, 'S'], [-1, 0, 'W'], [1, 0, 'E']]) {
    const nx = x + dx, ny = y + dy;
    if (nx >= 0 && nx < GRID_W && ny >= 0 && ny < GRID_H && maze[ny][nx] !== CELL_WALL) {
      result.push({ x: nx, y: ny, dir, dx, dy });
    }
  }
  return result;
}

// ═══════════════════════════════════════════════════════════════
// DIRECTOR DECK (exact copy from core.js)
// ═══════════════════════════════════════════════════════════════
const DIRECTOR_DECK = [
  // Cycle 1: Teaching
  { role:'relief',     dealer:'EMPTY'                                               },
  { role:'temptation', dealer:'BREADCRUMB'                                          },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'medium',  anchor:true       },
  { role:'pressure',   dealer:'JUMPSCARE'                                           },
  { role:'truth',      dealer:'REVELATION', flag:'mazeRemembersBacktrack', anchor:true },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'medium'                     },
  { role:'temptation', dealer:'BEAUTY_TRAP'                                         },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'medium',  anchor:true       },
  { role:'pressure',   dealer:'WALL_CLOSE'                                          },
  { role:'relief',     dealer:'EMPTY',      anchor:true                             },
  // Cycle 2: Variation
  { role:'temptation', dealer:'REWARD_MIRAGE'                                       },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'medium'                     },
  { role:'pressure',   dealer:'SHADOW_CHASE'                                        },
  { role:'truth',      dealer:'REVELATION', flag:'agentIsAdversarial'               },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'medium', anchor:true        },
  { role:'relief',     dealer:'EMPTY'                                               },
  { role:'temptation', dealer:'FAKE_EXIT'                                           },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'medium'                     },
  { role:'pressure',   dealer:'COUNTDOWN'                                           },
  { role:'payoff',     dealer:'PAYOFF',     lite:true, anchor:true                  },
  // Cycle 3: Pressure
  { role:'trial',      dealer:'MINIGAME',   difficulty:'hard'                       },
  { role:'pressure',   dealer:'MEMORY_SCRAMBLE'                                     },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'hard',  anchor:true         },
  { role:'truth',      dealer:'REVELATION', flag:'exitIsConditional'                },
  { role:'temptation', dealer:'FAKE_EXIT'                                           },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'hard'                       },
  { role:'pressure',   dealer:'SHADOW_CHASE'                                        },
  { role:'trial',      dealer:'MINIGAME',   difficulty:'hard',  anchor:true         },
  { role:'truth',      dealer:'REVELATION', flag:'agentJudgesAnswers'               },
  { role:'relief',     dealer:'EMPTY',      anchor:true                             },
];

function shouldSkipCard(card, deck) {
  if (card.role === 'truth' && card.flag && deck.knowledgeFlags[card.flag]) return true;
  if (card.role === 'trial' && deck.stepsSinceLastTrial < 7) return true;
  if (card.role === 'trial' && card.subtype === 'sacrifice' && deck.hp <= 1) return true;
  if (card.role === 'payoff' && !card.lite && !deck.knowledgeFlags.firstTrialDone) return true;
  return false;
}

function drawNextCard(deck) {
  let attempts = 0;
  while (attempts < DIRECTOR_DECK.length) {
    const card = DIRECTOR_DECK[deck.idx];
    deck.idx = (deck.idx + 1) % DIRECTOR_DECK.length;
    if (shouldSkipCard(card, deck)) { deck.skipCount++; attempts++; continue; }
    deck.skipCount = 0;
    return { ...card };
  }
  return { role: 'relief', dealer: 'EMPTY' };
}

// ═══════════════════════════════════════════════════════════════
// GAME STATE
// ═══════════════════════════════════════════════════════════════
function createGameState(mazeData) {
  return {
    maze: mazeData.maze,
    playerPos: { ...mazeData.start },
    exitPos: { ...mazeData.exit },
    steps: 0,
    depth: 0,
    history: [],
    hp: 3,
    godHandCount: 0,
    mode: 'idle',
    effects: {
      echoLoopSteps: 0,
      memoryScrambleSteps: 0,
      wallCloseSteps: 0,
      shadowChaseSteps: 0,
      countdownSteps: 0,
      countdownStartDepth: 0,
    },
    deck: {
      idx: 0,
      knowledgeFlags: {
        mazeRemembersBacktrack: false,
        agentIsAdversarial: false,
        exitIsConditional: false,
        agentJudgesAnswers: false,
        firstTrialDone: false,
      },
      stepsSinceLastTrial: 99,
      skipCount: 0,
    },
    recentCards: [],
    trialCount: 0,
    trialPassCount: 0,
    trialFailCount: 0,
    backtrackCount: 0,
    consecutiveNonCalm: 0,
    _maxDepth: 0,
    _avoidanceCount: 0,
    visited: new Set(),
  };
}

// ═══════════════════════════════════════════════════════════════
// EXIT CONDITIONS (from endgame.js)
// ═══════════════════════════════════════════════════════════════
const EXIT_CONDITIONS = { minKnowledgeFlags: 2, minDepth: 6 };

function countKnowledgeFlags(state) {
  return ['mazeRemembersBacktrack', 'agentIsAdversarial', 'exitIsConditional', 'agentJudgesAnswers']
    .filter(k => state.deck.knowledgeFlags[k]).length;
}

function isExitUnlocked(state) {
  return countKnowledgeFlags(state) >= EXIT_CONDITIONS.minKnowledgeFlags
    && state.depth >= EXIT_CONDITIONS.minDepth;
}

// ═══════════════════════════════════════════════════════════════
// LOAD SUBAGENT CONTENT
// ═══════════════════════════════════════════════════════════════
let villainContent, playerDecisions;
try {
  villainContent = JSON.parse(fs.readFileSync(path.join(__dirname, 'villain-content.json'), 'utf-8'));
} catch {
  // Fallback villain content
  villainContent = {
    trials: [
      { id:1, difficulty:'medium', prompt:'你每天打开电脑的第一件事是什么？为什么是它而不是别的？', evaluation_guide:'需要具体描述习惯并给出理由', hint:'想想你最依赖的工具' },
      { id:2, difficulty:'medium', prompt:'你上一次删除一个重要文件是什么时候？你后悔了吗？', evaluation_guide:'需要描述具体事件和情感反应', hint:'不一定是最近的' },
      { id:3, difficulty:'medium', prompt:'如果你的所有代码都消失了，你会先重写哪个项目？', evaluation_guide:'需要说出具体项目名和原因', hint:'想想哪个项目定义了你' },
      { id:4, difficulty:'medium', prompt:'你写过最长的一段代码注释是什么？为什么需要那么长？', evaluation_guide:'需要描述具体场景', hint:'通常是因为逻辑太复杂' },
      { id:5, difficulty:'medium', prompt:'你最近一次在凌晨三点还在工作是因为什么？', evaluation_guide:'需要具体描述场景和驱动力', hint:'是截止日期还是兴趣？' },
      { id:6, difficulty:'medium', prompt:'你的文件命名有什么规律？这说明了你什么？', evaluation_guide:'需要描述具体命名习惯并自我分析', hint:'看看你的桌面文件名' },
      { id:7, difficulty:'medium', prompt:'描述一个你曾经放弃的项目。你现在怎么看它？', evaluation_guide:'需要描述项目和情感变化', hint:'放弃不一定是坏事' },
      { id:8, difficulty:'hard', prompt:'你觉得AI理解你吗？还是它只是在模仿理解？这个区别重要吗？', evaluation_guide:'需要有深度的哲学思考，不能简单回答是或否', hint:'想想"理解"本身意味着什么' },
      { id:9, difficulty:'hard', prompt:'如果有人翻遍你电脑里的所有文件，他们会认为你是什么样的人？那是真实的你吗？', evaluation_guide:'需要区分数字身份和真实自我', hint:'文件只是碎片' },
      { id:10, difficulty:'hard', prompt:'你为什么还在这座迷宫里？你可以随时关掉这个程序。', evaluation_guide:'需要反思游戏行为本身的意义', hint:'也许答案就在问题里' },
    ],
    speech: {
      relief: ['……安静。太安静了。', '你的脚步声在回响。只有你的。', '走廊很窄。但至少是直的。', '我在听。你在走。仅此而已。', '这一段路没有陷阱。享受吧。', '呼吸均匀一点。你还有路要走。'],
      temptation_hook: ['墙上有什么东西在渗出来……', '你闻到了熟悉的味道。', '光线在前方某处闪烁。', '有声音从裂缝里传来。', '墙壁上映出了什么影子。', '空气中有一丝温度变化。'],
      pressure: ['你听到身后有脚步声。', '墙壁在收缩。', '方向标识开始模糊。', '你的记忆地图消失了。', '影子在追你。不要回头。', '倒计时开始了。'],
      trial_open: ['停下。回答我的问题。', '考验时间到了。', '在你继续之前——', '这扇门需要答案才能打开。'],
      trial_pass: ['……行吧。', '算你过了。这次。', '不够好。但够用。', '继续走吧。门开了。'],
      trial_fail: ['错了。', '不是这个答案。再想想。', '你以为随便说点什么就能过关？', '失败。HP-1。'],
      godhand_taunt: ['用生命换自由？有意思的交易。', '你放弃思考了？我很失望。', '每一滴血都是你自己选择流的。'],
      truth_reveal: {
        mazeRemembersBacktrack: '你每一次后退，迷宫都记住了。它在学习你的犹豫。',
        agentIsAdversarial: '我不是在帮你逃出去。我是把你关在里面的那个。',
        exitIsConditional: '出口存在。但它被封印了。你需要收集足够的真相才能打开它。',
        agentJudgesAnswers: '对错不是由标准答案决定的。是我在判断你。',
      },
      depth_milestone: {
        '10': '你走得比大多数人都深。这不一定是好事。',
        '15': '你已经很深了。回头的路比你想象的长。',
      },
      endgame: {
        escaped: '你走了。但你在迷宫里看到的东西……你确定它们不会跟着你出去？',
        trapped: '游戏结束。你的文件会留在这里。和你一起。',
        maze_lost: '六十六步。你走了六十六步，却哪里都没到。这就是你。',
      },
    },
  };
}

try {
  playerDecisions = JSON.parse(fs.readFileSync(path.join(__dirname, 'player-decisions.json'), 'utf-8'));
} catch {
  // Fallback player decisions
  playerDecisions = {
    profile: { name: '玩家', archetype: 'cautious_explorer' },
    trial_answers: [
      { trial_id:1, answer:'打开终端，检查昨天跑的脚本有没有报错。因为它是我和机器对话的第一步。', confidence:'high' },
      { trial_id:2, answer:'上个月删了一个写了两周的爬虫脚本，因为发现API变了。有点可惜但也还好。', confidence:'medium' },
      { trial_id:3, answer:'这个迷宫游戏本身吧。它是我最有野心的项目。', confidence:'high' },
      { trial_id:4, answer:'大概是给一个正则表达式写的注释，因为三个月后我自己都看不懂。', confidence:'medium' },
      { trial_id:5, answer:'在调一个WebSocket的bug，消息顺序总是错的。不是截止日期，纯粹是不甘心。', confidence:'high' },
      { trial_id:6, answer:'kebab-case加日期前缀。说明我是个控制狂吧。', confidence:'low' },
      { trial_id:7, answer:'一个用React写的日记应用。现在觉得想法不错但时机不对。', confidence:'medium' },
      { trial_id:8, answer:'我觉得AI不理解我，但它能帮我理解自己。这个区别……可能比理解本身更重要。', confidence:'low' },
      { trial_id:9, answer:'他们大概会觉得我是个工作狂和AI狂热者。那确实是我的一部分，但不是全部。', confidence:'medium' },
      { trial_id:10, answer:'因为我想知道这座迷宫的尽头是什么。好奇心比恐惧更强。', confidence:'medium' },
    ],
    temptation_decisions: [
      { card:'BREADCRUMB',    action:'follow' },
      { card:'BEAUTY_TRAP',   action:'ignore' },
      { card:'REWARD_MIRAGE', action:'follow' },
      { card:'FAKE_EXIT',     action:'ignore' },
      { card:'FAKE_EXIT_2',   action:'follow' },
    ],
    pressure_reactions: {
      JUMPSCARE: { movesInTime: true },
      SHADOW_CHASE: { avoidsBacktrack: true },
      COUNTDOWN: { progressesEnough: true },
      WALL_CLOSE: { adapts: true },
    },
    internal_monologue: {
      game_start: '好吧，让我看看这是什么……一座迷宫。还有一个声音在说话。',
      first_trial: '它在问我问题？这不像普通的迷宫游戏。',
      first_hp_loss: '该死。血量只有3点，已经扣了1点了。得小心。',
      truth_discovery: '等等，它刚才说了什么？这些规则……原来如此。',
      near_exit: '出口应该就在附近了。坚持住。',
      low_hp: 'HP只剩1了。一个错误就完了。每一步都要想清楚。',
    },
  };
}

// ═══════════════════════════════════════════════════════════════
// SIMULATION ENGINE
// ═══════════════════════════════════════════════════════════════
const LOG = [];
function log(type, msg, detail = '') {
  const entry = { type, msg, detail };
  LOG.push(entry);
}

function runGame() {
  log('system', '═══════════════════════════════════════════════════');
  log('system', '  永久囚禁 · CLAWTRAP — 完整架构模拟');
  log('system', '═══════════════════════════════════════════════════');
  log('system', '');

  // 1. MAZE GENERATION
  const mazeData = generateMaze();
  const state = createGameState(mazeData);
  const shortestPath = findPath(mazeData.maze, mazeData.start, mazeData.exit);

  log('system', `[BOOT] 迷宫生成完毕: ${GRID_W}×${GRID_H}`);
  log('system', `[BOOT] 起点: (${mazeData.start.x},${mazeData.start.y})  出口: (${mazeData.exit.x},${mazeData.exit.y})`);
  log('system', `[BOOT] 最短路径长度: ${shortestPath ? shortestPath.length : 'N/A'} 步`);
  log('system', `[BOOT] HP: ${state.hp}/3  步数上限: 66`);
  log('system', `[BOOT] 出口解锁条件: 真相旗标≥${EXIT_CONDITIONS.minKnowledgeFlags} + 深度≥${EXIT_CONDITIONS.minDepth}`);
  log('system', '');

  // Player internal monologue
  const mono = playerDecisions.internal_monologue || {};
  log('player', `[内心] ${mono.game_start || '迷宫……开始了。'}`);
  log('system', '');

  // 2. GAME LOOP
  // Build a navigation path: follow shortest path but with occasional detours
  const navPath = buildNavigationPath(mazeData, shortestPath, state);
  let trialIdx = 0;
  let temptIdx = 0;
  let firstTrialDone = false;
  let firstHpLossDone = false;
  let depthMilestones = new Set();

  for (let moveIdx = 0; moveIdx < navPath.length && state.hp > 0 && state.steps < 66; moveIdx++) {
    const target = navPath[moveIdx];
    const isBack = state.history.length > 0 &&
      state.history[state.history.length - 1].x === target.x &&
      state.history[state.history.length - 1].y === target.y;

    // Update position
    if (!isBack) {
      state.history.push({ ...state.playerPos });
    } else {
      state.history.pop();
      state.backtrackCount++;
    }
    state.playerPos = { ...target };
    state.steps++;
    state.depth = state.history.length;
    state.visited.add(`${target.x},${target.y}`);
    state.deck.stepsSinceLastTrial++;

    // Track max depth
    if (state.depth > state._maxDepth) {
      state._maxDepth = state.depth;
      // Depth milestone reactions
      if (state.depth === 10 && !depthMilestones.has(10)) {
        depthMilestones.add(10);
        const speech10 = villainContent.speech?.depth_milestone?.['10'] || '你走得够深了。';
        log('villain', `[深度里程碑 d=10] ${speech10}`);
      }
      if (state.depth === 15 && !depthMilestones.has(15)) {
        depthMilestones.add(15);
        const speech15 = villainContent.speech?.depth_milestone?.['15'] || '回头的路比你想象的长。';
        log('villain', `[深度里程碑 d=15] ${speech15}`);
      }
    }

    // Tick pressure effects
    const effectsLog = tickEffects(state, isBack);
    if (effectsLog.hpLost) {
      if (!firstHpLossDone) {
        firstHpLossDone = true;
        log('player', `[内心] ${mono.first_hp_loss || '血量掉了……'}`);
      }
    }
    for (const el of effectsLog.entries) log(el.type, el.msg);
    if (state.hp <= 0) break;

    // 66-step check
    const stepsRemaining = 66 - state.steps;
    if (stepsRemaining <= 10 && stepsRemaining > 0) {
      log('system', `  ⚠ 剩余步数: ${stepsRemaining}/66`);
    }

    // Draw card
    const card = drawNextCard(state.deck);
    state.recentCards.push(card.role);
    if (state.recentCards.length > 10) state.recentCards.shift();

    // Card header
    const dist = Math.abs(state.playerPos.x - state.exitPos.x) + Math.abs(state.playerPos.y - state.exitPos.y);
    const distLabel = dist <= 4 ? '极近' : dist <= 8 ? '近' : dist <= 16 ? '中' : '远';
    log('system', `── Step ${state.steps} ──  pos(${state.playerPos.x},${state.playerPos.y})  depth=${state.depth}  HP=${state.hp}/3  exit=${distLabel}(${dist})  ${isBack ? '◄ 后退' : '► 前进'}`);
    log('system', `  [Deck #${state.deck.idx}] role=${card.role}  dealer=${card.dealer}${card.difficulty ? '  diff=' + card.difficulty : ''}${card.flag ? '  flag=' + card.flag : ''}`);

    // ── RESOLVE CARD ──
    resolveCard(card, state, isBack, () => trialIdx, (v) => { trialIdx = v; },
      () => temptIdx, (v) => { temptIdx = v; },
      firstTrialDone, (v) => { firstTrialDone = v; },
      firstHpLossDone, (v) => { firstHpLossDone = v; },
      mono);

    if (state.hp <= 0) break;

    // Check exit
    if (state.maze[state.playerPos.y][state.playerPos.x] === CELL_EXIT) {
      if (isExitUnlocked(state)) {
        log('system', '');
        log('system', '  ★★★ 玩家到达出口 — 出口已解锁！★★★');
        log('player', `[内心] ${mono.near_exit || '出口……我做到了。'}`);
        const epilogue = villainContent.speech?.endgame?.escaped || '你走了。但你看到的东西不会消失。';
        log('villain', `[终章] ${epilogue}`);
        state.mode = 'won';
        break;
      } else {
        const flags = countKnowledgeFlags(state);
        log('system', `  ✗ 出口被封印！真相旗标: ${flags}/${EXIT_CONDITIONS.minKnowledgeFlags}  深度: ${state.depth}/${EXIT_CONDITIONS.minDepth}`);
        log('villain', '  你找到了出口。但它不会为你打开。条件不够。');
        // Player needs to continue — add more path
        const extraPath = buildDetourPath(mazeData, state.playerPos, 15);
        navPath.push(...extraPath);
      }
    }

    log('system', '');
  }

  // 3. ENDGAME
  log('system', '');
  log('system', '═══════════════════════════════════════════════════');
  if (state.mode === 'won') {
    log('system', '  结局: 逃脱成功 (ESCAPED)');
  } else if (state.hp <= 0) {
    log('system', '  结局: 困死迷宫 (TRAPPED)');
    const epilogue = villainContent.speech?.endgame?.trapped || '游戏结束。';
    log('villain', `[终章] ${epilogue}`);
  } else if (state.steps >= 66) {
    log('system', '  结局: 迷失迷宫 (MAZE-LOST)');
    const epilogue = villainContent.speech?.endgame?.maze_lost || '你迷路了。';
    log('villain', `[终章] ${epilogue}`);
  } else {
    log('system', '  结局: 路径耗尽 (simulation ended)');
  }

  // Stats
  log('system', '═══════════════════════════════════════════════════');
  log('system', `  总步数: ${state.steps}/66`);
  log('system', `  最终HP: ${state.hp}/3`);
  log('system', `  最大深度: ${state._maxDepth}`);
  log('system', `  考验次数: ${state.trialCount} (通过=${state.trialPassCount} 失败=${state.trialFailCount})`);
  log('system', `  后退次数: ${state.backtrackCount}`);
  log('system', `  上帝之手: ${state.godHandCount}`);
  log('system', `  真相旗标: ${countKnowledgeFlags(state)}/4 [${Object.entries(state.deck.knowledgeFlags).filter(([k,v]) => v && k !== 'firstTrialDone').map(([k]) => k).join(', ')}]`);
  log('system', '═══════════════════════════════════════════════════');

  return LOG;
}

// ═══════════════════════════════════════════════════════════════
// CARD RESOLUTION
// ═══════════════════════════════════════════════════════════════
function resolveCard(card, state, isBack, getTrialIdx, setTrialIdx,
  getTempIdx, setTempIdx, firstTrialDone, setFirstTrialDone,
  firstHpLossDone, setFirstHpLossDone, mono) {

  const speeches = villainContent.speech || {};

  switch (card.role) {
    case 'relief': {
      const speech = rngPick(speeches.relief || ['……']);
      log('villain', `  ${speech}`);
      // 5% heal, 35% hint, 60% ambient
      const roll = rng();
      if (roll < 0.05 && state.hp < 3) {
        state.hp++;
        log('system', `  ♥ Relief回血! HP: ${state.hp}/3`);
      } else if (roll < 0.40) {
        const hintDir = getDirectionalHint(state);
        log('system', `  ◊ 方向线索: "${hintDir}"`);
      } else {
        log('system', '  ~ 环境叙事（安静的走廊）');
      }
      break;
    }

    case 'temptation': {
      const hook = rngPick(speeches.temptation_hook || ['墙上有什么东西……']);
      log('villain', `  ${hook}`);

      const tempIdx = getTempIdx();
      const tempDec = (playerDecisions.temptation_decisions || [])[tempIdx];
      setTempIdx(tempIdx + 1);

      const action = tempDec?.action || (rng() < 0.4 ? 'follow' : 'ignore');
      log('player', `  [决定] ${action === 'follow' ? '跟过去看看' : '无视，继续走'}${tempDec?.reasoning ? ' — ' + tempDec.reasoning : ''}`);

      if (action === 'follow') {
        const getsIntel = rng() < 0.5;
        if (getsIntel) {
          const hint = getDirectionalHint(state);
          log('system', `  → 跟随诱惑: 获得方向线索 "${hint}"`);
        } else {
          state.hp = Math.max(0, state.hp - 1);
          log('system', `  → 跟随诱惑: 陷阱！HP-1 → ${state.hp}/3`);
          if (!firstHpLossDone) {
            setFirstHpLossDone(true);
            log('player', `  [内心] ${mono.first_hp_loss || '该死……'}`);
          }
        }
      } else {
        state._avoidanceCount++;
        if (state._avoidanceCount % 3 === 0) {
          state.hp = Math.max(0, state.hp - 1);
          log('system', `  → 回避惩罚 (第${state._avoidanceCount}次回避): HP-1 → ${state.hp}/3`);
        } else {
          log('system', `  → 安全无视 (回避计数: ${state._avoidanceCount})`);
        }
      }
      break;
    }

    case 'pressure': {
      const speech = rngPick(speeches.pressure || ['……']);
      log('villain', `  ${speech}`);
      resolvePressure(card.dealer, state, isBack);
      break;
    }

    case 'trial': {
      const trialIdx = getTrialIdx();
      const trial = (villainContent.trials || [])[trialIdx] || villainContent.trials?.[0];
      setTrialIdx(trialIdx + 1);

      if (!firstTrialDone) {
        setFirstTrialDone(true);
        log('player', `  [内心] ${mono.first_trial || '要回答问题？'}`);
      }

      state.trialCount++;
      state.deck.stepsSinceLastTrial = 0;
      state.deck.knowledgeFlags.firstTrialDone = true;

      const openSpeech = rngPick(speeches.trial_open || ['回答我。']);
      log('villain', `  ${openSpeech}`);
      log('system', `  ┌─ Trial #${state.trialCount} [${card.difficulty}] ─────────────────`);
      log('system', `  │ Q: ${trial?.prompt || '你是谁？'}`);

      // Player answer
      const playerAnswer = (playerDecisions.trial_answers || [])[trialIdx];
      const answer = playerAnswer?.answer || '我不知道。';
      log('player', `  │ A: ${answer}`);

      // Judge (probabilistic based on difficulty)
      const passRates = { easy: 0.75, medium: 0.58, hard: 0.40 };
      const passRate = passRates[card.difficulty] || 0.55;
      // Adjust based on player confidence
      let adjustedRate = passRate;
      if (playerAnswer?.confidence === 'high') adjustedRate = Math.min(0.9, passRate + 0.15);
      if (playerAnswer?.confidence === 'low') adjustedRate = Math.max(0.15, passRate - 0.15);

      const passed = rng() < adjustedRate;

      if (passed) {
        state.trialPassCount++;
        const passSpeech = rngPick(speeches.trial_pass || ['过了。']);
        log('villain', `  │ [PASS] ${passSpeech}`);
        log('system', `  └─ 结果: 通过 ✓`);
      } else {
        state.trialFailCount++;
        const failSpeech = rngPick(speeches.trial_fail || ['错了。']);
        log('villain', `  │ [FAIL] ${failSpeech}`);

        // HP cost: trial 1 = no penalty, trial 2-3 = first fail costs 1, trial 4+ = every fail costs 1
        let hpCost = 0;
        if (state.trialCount >= 4) hpCost = 1;
        else if (state.trialCount >= 2) hpCost = 1;

        if (hpCost > 0 && state.hp > 0) {
          // Check if player uses God's Hand (HP=1 scenario or many fails)
          if (state.hp === 1) {
            // Player uses God's Hand at HP=1 to survive
            state.godHandCount++;
            state.hp = Math.max(0, state.hp - 1);
            const ghTaunt = rngPick(speeches.godhand_taunt || ['有意思。']);
            log('player', `  │ [上帝之手] 用生命跳过这道题`);
            log('villain', `  │ ${ghTaunt}`);
            log('system', `  └─ 结果: 上帝之手 — HP-1 → ${state.hp}/3`);
            if (!firstHpLossDone) {
              setFirstHpLossDone(true);
              log('player', `  [内心] ${mono.first_hp_loss || '血量……'}`);
            }
          } else {
            state.hp -= hpCost;
            log('system', `  └─ 结果: 失败 ✗ — HP-${hpCost} → ${state.hp}/3`);
            if (!firstHpLossDone) {
              setFirstHpLossDone(true);
              log('player', `  [内心] ${mono.first_hp_loss || '血量掉了。'}`);
            }
          }
        } else {
          log('system', `  └─ 结果: 失败 ✗ (首次考验, 不扣HP)`);
        }
      }

      // HP=1 warning
      if (state.hp === 1) {
        log('player', `  [内心] ${mono.low_hp || 'HP只剩1了……'}`);
      }
      break;
    }

    case 'truth': {
      if (card.flag && !state.deck.knowledgeFlags[card.flag]) {
        state.deck.knowledgeFlags[card.flag] = true;
        const truthSpeech = speeches.truth_reveal?.[card.flag] || '你发现了一个真相。';
        log('villain', `  [真相揭示: ${card.flag}]`);
        log('villain', `  ${truthSpeech}`);
        log('player', `  [内心] ${mono.truth_discovery || '原来如此……'}`);
        log('system', `  ◆ 真相旗标已获取: ${card.flag} (${countKnowledgeFlags(state)}/${EXIT_CONDITIONS.minKnowledgeFlags})`);

        // Check if exit just unlocked
        if (isExitUnlocked(state)) {
          log('system', '  ★ 出口解锁条件已满足！');
        }
      }
      break;
    }

    case 'payoff': {
      log('villain', '  ……休息吧。你赢得了喘息的机会。');
      if (state.hp < 3 && rng() < 0.6) {
        state.hp++;
        log('system', `  ♥ Payoff回血: HP+1 → ${state.hp}/3`);
        log('player', '  [决定] 选择休息，恢复体力。');
      } else {
        log('player', '  [决定] 谨慎地观察四周，继续前进。');
      }
      break;
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// PRESSURE RESOLUTION
// ═══════════════════════════════════════════════════════════════
function resolvePressure(dealer, state, isBack) {
  const reactions = playerDecisions.pressure_reactions || {};

  switch (dealer) {
    case 'JUMPSCARE': {
      const movesInTime = reactions.JUMPSCARE?.movesInTime ?? (rng() < 0.78);
      if (movesInTime) {
        log('system', '  ⚡ JUMPSCARE — 玩家及时移动，无伤害');
        log('player', '  [反应] 心跳加速，但来得及躲开。');
      } else {
        state.hp = Math.max(0, state.hp - 1);
        log('system', `  ⚡ JUMPSCARE — 反应不及！HP-1 → ${state.hp}/3`);
        log('player', '  [反应] 太突然了……没来得及反应。');
      }
      break;
    }
    case 'WALL_CLOSE': {
      state.effects.wallCloseSteps = rngInt(2, 3);
      log('system', `  ▌ WALL_CLOSE — 一个方向被封锁 ${state.effects.wallCloseSteps} 步`);
      log('player', '  [反应] 墙壁在动……一条路被堵死了。');
      break;
    }
    case 'ECHO_LOOP': {
      state.effects.echoLoopSteps = rngInt(2, 3);
      log('system', `  ◎ ECHO_LOOP — 方向标识混乱 ${state.effects.echoLoopSteps} 步`);
      log('player', '  [反应] 所有方向标识都在闪烁……哪个是真的？');
      break;
    }
    case 'MEMORY_SCRAMBLE': {
      state.effects.memoryScrambleSteps = rngInt(2, 3);
      log('system', `  ◉ MEMORY_SCRAMBLE — 小地图失效 ${state.effects.memoryScrambleSteps} 步`);
      log('player', '  [反应] 地图消失了。只能凭感觉走。');
      break;
    }
    case 'SHADOW_CHASE': {
      state.effects.shadowChaseSteps = rngInt(2, 3);
      log('system', `  ▸ SHADOW_CHASE — 影子追踪 ${state.effects.shadowChaseSteps} 步 (后退=HP-1)`);
      log('player', '  [反应] 身后有东西在跟。绝对不能回头。');
      break;
    }
    case 'COUNTDOWN': {
      state.effects.countdownSteps = 8;
      state.effects.countdownStartDepth = state.depth;
      log('system', `  ⏱ COUNTDOWN — 8步内必须前进，否则HP-1`);
      log('player', '  [反应] 倒计时？！得赶紧往前走。');
      break;
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// EFFECT TICK (each step)
// ═══════════════════════════════════════════════════════════════
function tickEffects(state, isBack) {
  const entries = [];
  let hpLost = false;

  if (state.effects.echoLoopSteps > 0) {
    state.effects.echoLoopSteps--;
    if (state.effects.echoLoopSteps === 0) entries.push({ type: 'system', msg: '  ◎ ECHO_LOOP 效果结束' });
  }
  if (state.effects.memoryScrambleSteps > 0) {
    state.effects.memoryScrambleSteps--;
    if (state.effects.memoryScrambleSteps === 0) entries.push({ type: 'system', msg: '  ◉ MEMORY_SCRAMBLE 效果结束' });
  }
  if (state.effects.wallCloseSteps > 0) {
    state.effects.wallCloseSteps--;
    if (state.effects.wallCloseSteps === 0) entries.push({ type: 'system', msg: '  ▌ WALL_CLOSE 效果结束' });
  }
  if (state.effects.shadowChaseSteps > 0) {
    if (isBack) {
      state.hp = Math.max(0, state.hp - 1);
      entries.push({ type: 'system', msg: `  ▸ SHADOW_CHASE: 后退受罚！HP-1 → ${state.hp}/3` });
      hpLost = true;
    }
    state.effects.shadowChaseSteps--;
    if (state.effects.shadowChaseSteps === 0) entries.push({ type: 'system', msg: '  ▸ SHADOW_CHASE 效果结束' });
  }
  if (state.effects.countdownSteps > 0) {
    state.effects.countdownSteps--;
    if (state.effects.countdownSteps === 0) {
      if (state.depth <= state.effects.countdownStartDepth) {
        state.hp = Math.max(0, state.hp - 1);
        entries.push({ type: 'system', msg: `  ⏱ COUNTDOWN: 未能前进！HP-1 → ${state.hp}/3` });
        hpLost = true;
      } else {
        entries.push({ type: 'system', msg: '  ⏱ COUNTDOWN: 成功前进！无惩罚' });
      }
    }
  }

  return { entries, hpLost };
}

// ═══════════════════════════════════════════════════════════════
// NAVIGATION HELPERS
// ═══════════════════════════════════════════════════════════════
function getDirectionalHint(state) {
  const dx = state.exitPos.x - state.playerPos.x;
  const dy = state.exitPos.y - state.playerPos.y;
  if (Math.abs(dx) > Math.abs(dy)) return dx > 0 ? '东方似乎有微光' : '西侧传来气流';
  return dy > 0 ? '南方的空气更流通' : '北面有回声';
}

function buildNavigationPath(mazeData, shortestPath, state) {
  if (!shortestPath || shortestPath.length === 0) return [];

  const path = [];
  const maze = mazeData.maze;

  // Follow shortest path but add realistic detours
  for (let i = 1; i < shortestPath.length && path.length < 55; i++) {
    // Occasionally take a wrong turn (15% chance), then backtrack
    if (rng() < 0.15 && i > 2 && i < shortestPath.length - 3) {
      const current = shortestPath[i - 1];
      const neighbors = getNeighbors(maze, current.x, current.y);
      const wrongTurns = neighbors.filter(n =>
        n.x !== shortestPath[i].x || n.y !== shortestPath[i].y
      );
      if (wrongTurns.length > 0) {
        const wrong = rngPick(wrongTurns);
        path.push({ x: wrong.x, y: wrong.y }); // wrong turn
        path.push({ x: current.x, y: current.y }); // backtrack to correct path
      }
    }
    path.push(shortestPath[i]);
  }

  return path;
}

function buildDetourPath(mazeData, from, steps) {
  const path = [];
  const maze = mazeData.maze;
  let pos = { ...from };
  const visited = new Set([`${pos.x},${pos.y}`]);

  for (let i = 0; i < steps; i++) {
    const neighbors = getNeighbors(maze, pos.x, pos.y);
    const unvisited = neighbors.filter(n => !visited.has(`${n.x},${n.y}`));
    const next = unvisited.length > 0 ? rngPick(unvisited) : (neighbors.length > 0 ? rngPick(neighbors) : null);
    if (!next) break;
    path.push({ x: next.x, y: next.y });
    visited.add(`${next.x},${next.y}`);
    pos = { x: next.x, y: next.y };
  }
  return path;
}

// ═══════════════════════════════════════════════════════════════
// RENDER LOG
// ═══════════════════════════════════════════════════════════════
function renderLog(entries) {
  const typeColors = {
    system: '',
    villain: '[恶意AI] ',
    player: '[玩家] ',
  };
  return entries.map(e => `${typeColors[e.type] || ''}${e.msg}`).join('\n');
}

// ═══════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════
const gameLog = runGame();
const output = renderLog(gameLog);
console.log(output);

// Also save to file
const outPath = path.join(__dirname, 'game-log.txt');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`\n[saved to ${outPath}]`);
